runmode: debug                 # 开发模式, debug, release, test
addr: :4096                  # HTTP绑定端口
name: mental-health              # API Server的名字
url: http://127.0.0.1:4096   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: ccnuinformationmanagementmentalhealth
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: mental_health
  addr: 127.0.0.1:3306
  username: root
  password: 123
default_user:
  username: health
  avatar: qen7rjp6a.bkt.clouddn.com/1-1597458748.png
  introduction: 该用户没有填写简介~
  phone: 无
  back_avatar: qen7rjp6a.bkt.clouddn.com/1-1597458748.png
oss:
  access_key: SkU
  secret_key:  YAn
  bucket_name: hjm1027
  domain_name: qen
app:
  app_id:
  app_secret: